# R/utils.R

utils::globalVariables(c(
  # Variables dynamically generated by gtsummary environments
  "var_type",
  "row_type",

  # gtsummary dynamic stat/p.value column names
  # (in case gtsummary evaluates them without quotes)
  "stat_0_2",
  "stat_0_1",
  "p.value_1",
  "p.value_4",

  # Variables used in specific RHS formula conditions or assertions
  "b"
))
