# R/utils.R

#' Backtick-quote a variable name for use inside a formula
#'
#' @description Wraps a variable name in backticks so `as.formula()` accepts
#' names with spaces (e.g. tibble columns like `` `Age Group` ``). Terms that
#' already contain formula operators (e.g. "BMI*Smoker", "Age:Smoker") are
#' left untouched, so interaction terms keep working as-is.
#' @param x Character vector of variable name(s)/term(s)
#' @return Character vector, backtick-quoted where needed
#' @noRd
bt <- function(x) {
  needs_quoting <- grepl(" ", x) & !grepl("[*:()+]", x)
  ifelse(needs_quoting, paste0("`", x, "`"), x)
}

#' Strip gtsummary's automatic stat-type suffix from a variable label
#'
#' @description `gtsummary::tbl_summary()` appends the statistic shown to
#' the row label (e.g. "Age, Median (IQR)", "Sex, n (%)") whenever the
#' column header doesn't already state it. Our tables state the statistic
#' in a custom header/spanner instead, so the per-row suffix is redundant
#' and is stripped here for a clean label.
#' @param x Character vector of rendered labels
#' @return Character vector with the suffix removed where present
#' @noRd
strip_stat_suffix <- function(x) {
  gsub(",\\s*(Mean \\(SD\\)|Median \\(IQR\\)|n \\(%\\)|n)$", "", x)
}

utils::globalVariables(c(
  # Variables dynamically generated by gtsummary environments
  "var_type",
  "row_type",

  # gtsummary dynamic stat/p.value column names
  # (in case gtsummary evaluates them without quotes)
  "stat_0_2",
  "stat_0_1",
  "p.value_1",
  "p.value_4",

  # Variables used in specific RHS formula conditions or assertions
  "b"
))
