# R/utils.R

#' Backtick-quote a variable name for use inside a formula
#'
#' @description Wraps a variable name in backticks so `as.formula()` accepts
#' names with spaces (e.g. tibble columns like `` `Age Group` ``). Terms that
#' already contain formula operators (e.g. "BMI*Smoker", "Age:Smoker") are
#' left untouched, so interaction terms keep working as-is.
#' @param x Character vector of variable name(s)/term(s)
#' @return Character vector, backtick-quoted where needed
#' @noRd
bt <- function(x) {
  needs_quoting <- grepl(" ", x) & !grepl("[*:()+]", x)
  ifelse(needs_quoting, paste0("`", x, "`"), x)
}

#' Strip gtsummary's automatic stat-type suffix from a variable label
#'
#' @description `gtsummary::tbl_summary()` appends the statistic shown to
#' the row label (e.g. "Age, Median (IQR)", "Sex, n (%)") whenever the
#' column header doesn't already state it. Our tables state the statistic
#' in a custom header/spanner instead, so the per-row suffix is redundant
#' and is stripped here for a clean label.
#' @param x Character vector of rendered labels
#' @return Character vector with the suffix removed where present
#' @noRd
strip_stat_suffix <- function(x) {
  gsub(",\\s*(Mean \\(SD\\)|Median \\(IQR\\)|n \\(%\\)|n)$", "", x)
}

#' Format P-values in MJMS style
#'
#' @description P-values to 3 decimal places; values below 0.001 are written
#' as "< 0.001" (with a space), following Arifin et al. (2016), MJMS 23(5):1-7.
#' Usable as a gtsummary `pvalue_fun`.
#' @param p Numeric vector of P-values
#' @param digits Number of decimal places (default 3)
#' @return Character vector
#' @noRd
mjms_pvalue <- function(p, digits = 3) {
  threshold <- 10^(-digits)
  out <- ifelse(
    p < threshold,
    paste0("< ", formatC(threshold, format = "f", digits = digits)),
    formatC(p, format = "f", digits = digits)
  )
  out[is.na(p)] <- NA_character_
  out
}

#' Build an MJMS table caption
#'
#' @description Returns "**Table :** caption (_n_ = N)." ending with a full
#' stop. Any trailing full stop and surrounding bold markers in `caption` are
#' removed first, so user captions with or without them give the same result.
#' @param caption Caption text
#' @param n Sample size to show; a number, a gtsummary glue string such as
#' "\{N\}", or NULL to omit
#' @return Character string (markdown)
#' @noRd
mjms_caption <- function(caption, n = NULL) {
  caption <- trimws(gsub("^\\*\\*|\\*\\*$", "", trimws(caption)))
  caption <- sub("\\.$", "", caption)
  n_part <- if (is.null(n)) "" else paste0(" (_n_ = ", n, ")")
  paste0("**Table :** ", caption, n_part, ".")
}

#' Add an MJMS abbreviation note to a gt table
#'
#' @description Adds the abbreviations as a gt footnote with no location, so
#' it is printed without a mark, before the lettered footnotes, with no
#' "Abbreviation:" prefix and ending with a full stop.
#' @param gt_tbl A gt table
#' @param abbreviation Character vector of abbreviations (joined with "; "),
#' or NULL to leave the table unchanged
#' @return A gt table
#' @noRd
add_abbreviation_note <- function(gt_tbl, abbreviation = NULL) {
  if (is.null(abbreviation) || all(!nzchar(trimws(abbreviation)))) {
    return(gt_tbl)
  }
  note <- paste(trimws(abbreviation), collapse = "; ")
  note <- sub("^Abbreviations?:\\s*", "", note)
  if (!grepl("\\.$", note)) note <- paste0(note, ".")
  gt::tab_footnote(gt_tbl, footnote = gt::md(note))
}

utils::globalVariables(c(
  # Variables dynamically generated by gtsummary environments
  "var_type",
  "row_type",

  # gtsummary dynamic stat/p.value column names
  # (in case gtsummary evaluates them without quotes)
  "stat_0_2",
  "stat_0_1",
  "p.value_1",
  "p.value_4",

  # Variables used in specific RHS formula conditions or assertions
  "b"
))
